import { SearchHeroSection } from '@/components/search/SearchHeroSection'
import { SearchInputSction } from '@/components/search/SearchInputSction'
import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
  title: 'Search | HJ',
  description: 'Generated by create next app',
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3000'),
  openGraph : {
    images : [
      {
        url : '/api/og?title=Search',
        width : 1200,
        height : 630,
      }
    ]
  }
}

const Search = () => {
  return (
    <div>
      <SearchHeroSection />
      <SearchInputSction />
    </div>
  )
}

export default Search