import { SearchHeroSection } from '@/components/search/SearchHeroSection'
import { SearchInputSction } from '@/components/search/SearchInputSction'
import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
  title: 'Search | HJ',
  description: 'Generated by create next app',
}

const Search = () => {
  return (
    <div>
      <SearchHeroSection />
      <SearchInputSction />
    </div>
  )
}

export default Search