import NotionPageRenderer from '@/components/notion/NotionPageRenderer'
import { Metadata } from 'next';
import { NotionAPI } from 'notion-client';
import { ExtendedRecordMap } from 'notion-types';
import React from 'react'

interface AboutProps{
  recordMap: ExtendedRecordMap;
}

export const metadata: Metadata = {
  title: 'About | HJ',
  description: 'Generated by create next app',
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3000'),
  openGraph : {
    images : [
      {
        url : '/api/og?title=About',
        width : 1200,
        height : 630,
      }
    ]
  }
}

export default async function About() { 
  const {recordMap} = await getAboutContent();

  return (
    <div>
      <NotionPageRenderer recordMap={recordMap} />
    </div>
  )
}

const getAboutContent = async (): Promise<AboutProps> => {
  const notion = new NotionAPI(); 
  const profileId = process.env.PROFILE_ID; 
  if(!profileId) throw new Error("PROFILE_ID is not defined");
  const recordMap = await notion.getPage(profileId);

  return {
    recordMap,
  };
};

export const revalidate = 600;