import { getDatabaseFromNotion } from "@/cms/notionClient";
import { CardSection } from "@/components/intro/CardSection";
import HeroSection from "@/components/intro/HeroSection";
import { ParsedDatabaseItemType, parseDatabaseItems } from "@/utils/parseDatabaseItems";
import { Metadata } from "next";
import { cache } from "react";

export interface HomeProps {
  databaseItems : ParsedDatabaseItemType[],
}

export const metadata: Metadata = {
  title: 'HJ',
  description: 'Generated by create next app',
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3000'),
  openGraph : {
    images : [
      {
        url : '/api/og?title=HJ',
        width : 1200,
        height : 630,
      }
    ]
  }
}
export default async function Home() {
  if(!process.env.DATABASE_ID) throw new Error("DATABASE_ID is not defined");
  const data = await getItem();

  return (
    <div>
      <HeroSection />
      <CardSection cardItems = {data}/>
    </div>
  )
}

// getStaticProps : 페이지 콘텐츠가 외부데이터에 연동된다 -> nextjs 13버전 이후 getStaticProps 사용안함
async function getData () {
  if(!process.env.DATABASE_ID) throw new Error("DATABASE_ID is not defined");
  const res = await getDatabaseFromNotion(process.env.DATABASE_ID);
  const parsedDatabaseItems = parseDatabaseItems(res);

  return parsedDatabaseItems;
}

//revalidate 사용하기 위해 react-cache 사용..? 맞나..?
const getItem = cache(async () => {
  if(!process.env.DATABASE_ID) throw new Error("DATABASE_ID is not defined");
  const res = await getDatabaseFromNotion(process.env.DATABASE_ID);
  const parsedDatabaseItems = parseDatabaseItems(res);

  return parsedDatabaseItems;
})